{% set version = "0.5.10" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-jskm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jskm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jskm/jskm_{{ version }}.tar.gz
  sha256: 55cd9c6be7ebf738d8f358c127519a13231f7a85b25d099d2e0837898a9ffbb2

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cmprsk
    - r-ggplot2
    - r-ggpubr
    - r-patchwork
    - r-scales
    - r-survey
    - r-survival
  run:
    - r-base
    - r-cmprsk
    - r-ggplot2
    - r-ggpubr
    - r-patchwork
    - r-scales
    - r-survey
    - r-survival

test:
  commands:
    - $R -e "library('jskm')"           # [not win]
    - "\"%R%\" -e \"library('jskm')\""  # [win]

about:
  home: https://jinseob2kim.github.io/jskm/
  dev_url: https://github.com/jinseob2kim/jskm
  license: Apache-2.0
  summary: The function 'jskm()' creates publication quality Kaplan-Meier plot with at risk tables below. 'svyjskm()' provides plot for weighted Kaplan-Meier estimator.
  license_family: Apache
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: jskm
# Title: Kaplan-Meier Plot with 'ggplot2'
# Version: 0.5.6
# Date: 2024-10-23
# Authors@R: c(person("Jinseob", "Kim", email = "jinseob2kim@gmail.com", role = c("aut", "cre"),  comment = c(ORCID = "0000-0002-9403-605X")), person("yoonkyoung", "Chun", email = "rachel200357@gmail.com", role = "aut"), person("Zarathu", role = c("cph", "fnd")) )
# Description: The function 'jskm()' creates publication quality Kaplan-Meier plot with at risk tables below. 'svyjskm()' provides plot for weighted Kaplan-Meier estimator.
# Depends: R (>= 3.4.0)
# License: Apache License 2.0
# Encoding: UTF-8
# Imports: ggplot2, ggpubr, survival, survey, scales, patchwork
# RoxygenNote: 7.3.2
# URL: https://github.com/jinseob2kim/jskm, https://jinseob2kim.github.io/jskm/
# BugReports: https://github.com/jinseob2kim/jstable/issues
# Suggests: testthat, knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2024-10-23 09:16:04 UTC; js
# Author: Jinseob Kim [aut, cre] (<https://orcid.org/0000-0002-9403-605X>), yoonkyoung Chun [aut], Zarathu [cph, fnd]
# Maintainer: Jinseob Kim <jinseob2kim@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-10-23 11:00:01 UTC
